config/routes.rb
Rails.application.routes.draw do
  devise_for  :admins, :path => 'sehatq/backyard',
              controllers: { registrations: "registrations" },
              :path_names => {
                :sign_in => "login",
                :sign_out => "logout",
              }

  root :to => "landing#index"

  get 'sehatq/backyard', to: "sehatq/backyard/home#index", as: 'home_dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated do
    root :to => 'sehatq/backyard/home#index'
  end

  namespace :sehatq do
    namespace :backyard do
      resources :home, only: %i[index]
      resources :admin
      resources :hospital
      resources :doctor
      resources :schedule_doctor
      resources :booking_doctor
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
end
  

app/controllers/admin/backyard/home_controller.rb
module Admin
  module Backyard
    class HomeController < ApplicationController
      before_action :authenticate_admin!
      def index
      end
    end
  end
end

app/controllers/sehatq/backyard/admin_controller.rb
module Sehatq
  module Backyard
    class AdminController < ApplicationController
      before_action :authenticate_admin!
      before_action :default_params, only: :index

      def index
        ransack_instance = Admin.all.ransack(params[:q])
        @admin_users = ransack_instance.result.page(params[:page]).per(params[:limit])
        render locals: { ransack_instance: ransack_instance }
      end

      def new
        @admin_user = Admin.new
      end

      def create
        @admin_user = Admin.new(admin_user_params)
        if @admin_user.save
          redirect_to sehatq_backyard_admin_index_path
        else
          return render 'new'
        end
      end

      def admin_user_params
        permitted = params.require(:admin_user)
        .permit(:name, :password, :email)
      end

      def default_params
        params[:limit] ||= 25
      end
    end
  end
end

app/controllers/sehatq/backyard/booking_doctor_controller.rb
module Sehatq
  module Backyard
    class BookingDoctorController < ApplicationController
      before_action :authenticate_admin!
      before_action :default_params, only: :index
      before_action :query, only: %i[new create]

      def index
        ransack_instance = BookingDoctor.all.ransack(params[:q])
        @booking_doctors = ransack_instance.result.page(params[:page]).per(params[:limit])
        render locals: { ransack_instance: ransack_instance }
      end

      def new
        @booking_doctor = BookingDoctor.new
      end

      def create
        @booking_doctor = BookingDoctor.new(schedule_doctor_params)
        if @booking_doctor.save
          redirect_to sehatq_backyard_booking_doctor_index_path
        else
          return render 'new'
        end
      end

      def schedule_doctor_params
        permitted = params.require(:booking_doctor)
        .permit(:customer_name, :schedule_doctor_id)
      end

      def query
       # Query
        # The maximum user can book within 30 minutes before the doctor starts the schedule.
        #A total of 10 users can book the same doctor.
        ctime = Time.now + 30.minutes
        @schedule_doctors = ScheduleDoctor.select("schedule_doctors.*").joins(:booking_doctors)
                                          .group("schedule_doctors.id")
                                          .having("count(booking_doctors.id) < ?", 10)
                                          .where("Date(schedule_doctors.schedule) > ?  ", Time.zone.today)
                                          .where.not("TIME(schedule_doctors.start_time) < ? AND Date(schedule_doctors.schedule) = ? ", ctime.strftime('%H:%M'), Time.zone.today)
      end


      def default_params
        params[:limit] ||= 25
      end
    end
  end
end

app/controllers/sehatq/backyard/doctor_controller.rb
module Sehatq
  module Backyard
    class DoctorController < ApplicationController
      before_action :authenticate_admin!
      before_action :default_params, only: :index

      def index
        ransack_instance = Doctor.all.ransack(params[:q])
        @doctors = ransack_instance.result.page(params[:page]).per(params[:limit])
        render locals: { ransack_instance: ransack_instance }
      end

      def new
        @hospitals = Hospital.all
        @doctor = Doctor.new
      end

      def create
        @doctor = Doctor.new(hospital_params)
        if @doctor.save
          redirect_to sehatq_backyard_doctor_index_path
        else
          @hospitals = Hospital.all
          return render 'new'
        end
      end

      def hospital_params
        permitted = params.require(:doctor)
                .permit(:name, :hospital_id)
      end

      def default_params
        params[:limit] ||= 25
      end
    end
  end
end

app/controllers/sehatq/backyard/home_controller.rb
module Sehatq
  module Backyard
    class HomeController < ApplicationController
      before_action :authenticate_admin!
      def index
      end
    end
  end
end

app/controllers/sehatq/backyard/hospital_controller.rb
module Sehatq
  module Backyard
    class HospitalController < ApplicationController
      before_action :authenticate_admin!
      before_action :default_params, only: :index

      def index
        ransack_instance = Hospital.all.ransack(params[:q])
        @hospitals = ransack_instance.result.page(params[:page]).per(params[:limit])
        render locals: { ransack_instance: ransack_instance }
      end

      def new
        @hospital = Hospital.new
      end

      def create
        @hospital = Hospital.new(hospital_params)
        if @hospital.save
          redirect_to sehatq_backyard_hospital_index_path
        else
          return render 'new'
        end
      end

      def hospital_params
        permitted = params.require(:hospital)
        .permit(:name, :address)
      end

      def default_params
        params[:limit] ||= 25
      end
    end
  end
end

app/controllers/sehatq/backyard/schedule_doctor_controller.rb
module Sehatq
  module Backyard
    class ScheduleDoctorController < ApplicationController
      before_action :authenticate_admin!
      before_action :default_params, only: :index

      def index
        ransack_instance = ScheduleDoctor.all.ransack(params[:q])
        @schedule_doctors = ransack_instance.result.page(params[:page]).per(params[:limit])
        render locals: { ransack_instance: ransack_instance }
      end

      def new
        @doctors = Doctor.all
        @schedule = ScheduleDoctor.new
      end

      def create
        @schedule = ScheduleDoctor.new(schedule_params)
        if @schedule.save
          redirect_to sehatq_backyard_schedule_doctor_index_path
        else
          @doctors = Doctor.all
          return render 'new'
        end
      end

      def schedule_params
        permitted = params.require(:schedule_doctor)
          .permit(:schedule, :doctor_id, :start_time, :end_time)
      end

      def default_params
        params[:limit] ||= 25
      end
    end
  end
end

app/views/sehatq/backyard/hospital/index.html.slim
= render 'sehatq/backyard/shared/header'

.ks-page-container.ks-dashboard-tabbed-sidebar-fixed-tabs
  .ks-column.ks-page
    .ks-page-header
      section.ks-title-and-subtitle
        .ks-title-block
          h3.ks-main-title Admin Management
    .ks-page-content
      .ks-page-content-body.ks-filemanager-page
        .ks-files
          .ks-header
            .ks-search.input-icon.icon-right.icon.icon-lg
              = search_form_for ransack_instance, url: sehatq_backyard_hospital_index_path do |f|
                = f.text_field :name_cont,
                              placeholder: "Search",
                              class: 'form-control', id: 'eg-search'
                span.icon-addon
                  span.la.la-search
            .ks-filters
              = button_to new_sehatq_backyard_hospital_path,
                      class: 'btn-primary btn',
                      method: :get do
                | Add Hospital
          .ks-content
            table.table.table-bordered
              thead
                tr
                  th width="150"  ID
                  th Name
                  th Adress
              tbody
                - @hospitals.each do |hospital|
                  tr
                    td
                      = hospital.id
                    td
                      = hospital.name
                    td 
                      = hospital.address
                - if @hospitals.empty?
                  td colspan="5" style="text-align: center;"
                    | Hospital can't be found, Please click "Add Hospital" to get a new hospital
                
            = paginate @hospitals

app/views/sehatq/backyard/hospital/new.html.slim
= render 'sehatq/backyard/shared/header'

.ks-page-container.ks-dashboard-tabbed-sidebar-fixed-tabs
  .ks-column.ks-page
    .ks-page-header
      section.ks-title-and-subtitle
        .ks-title-block
          .ks-sub-title Hospital Management
          h3.ks-main-title Add Hospital
    .ks-page-content
      .ks-page-content-body
        .ks-nav-body-wrapper
          .container-fluid
            .row
              .col-lg-4.offset-4
                div
                  = form_for @hospital, as: :hospital, url: sehatq_backyard_hospital_index_path, method: :post do |f|
                    .form-group.row
                      .col-lg-12
                        = f.label :name, 'Name'
                        = f.text_field :name, class: "form-control #{@hospital.errors[:name].any? ? 'error' : ''}"
                        span.is-message = flash_error?(@hospital, :name) || ''
                    .form-group.row
                        .col-lg-12
                          = f.label :address, 'Address'
                          = f.text_area :address, class: "form-control #{@hospital.errors[:address].any? ? 'error' : ''}"
                          small.is-message.text-danger = flash_error?(@hospital, :address) || ''
                    .form-group.row
                      .col-lg-12.text-right
                        = f.submit 'Add', class: "btn btn-primary"